### ISSUE TITLE
Latest version 2.2.5, 2.2.3 crashing with StackOverflowError

### ISSUE THREAD

**Issue by vovkab** [ksvc/KSYStreamer_Android#138]
Device Google Pixel (Android 7.0)

Affected versions:
 * 2.2.5
 * 2.2.3
 * 2.2.1

My gradle:
```gradle
compile "com.ksyun.media:libksylive-java:$ksyVersion"
compile "com.ksyun.media:libksylive-armv7a:$ksyVersion"
compile "com.ksyun.media:libksylive-arm64:$ksyVersion"
compile "com.ksyun.media:libksylive-x86:$ksyVersion"
```

Stack trace of the crash:

```stacktrace
03-02 11:55:52.853 D/Error: ERR: stack=java.lang.StackOverflowError: stack size 1037KB
  at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:172)
  at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
  at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
  at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
  ...
  at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
  at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
  at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
  at com.ksyun.media.player.https.a$2$1.verify(KsyHttpConnection.java:173)
  at com.android.okhttp.Connection.connectTls(Connection.java:239)
  at com.android.okhttp.Connection.connectSocket(Connection.java:199)
  at com.android.okhttp.Connection.connect(Connection.java:172)
  at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
  at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
  at io.fabric.sdk.android.services.network.HttpRequest.openOutput(HttpRequest.java:2450)
  at io.fabric.sdk.android.services.network.HttpRequest.startPart(HttpRequest.java:2463)
  at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2542)
  at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2526)
  at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2512)
  at com.crashlytics.android.core.DefaultCreateReportSpiCall.applyMultipartDataTo(DefaultCreateReportSpiCall.java:89)
  at com.crashlytics.android.core.DefaultCreateReportSpiCall.invoke(DefaultCreateReportSpiCall.java:61)
  at com.crashlytics.android.core.ReportUploader.forceUpload(ReportUploader.java:78)
  at com.crashlytics.android.core.ReportUploader$Worker.attemptUploadWithRetry(ReportUploader.java:211)
  at com.crashlytics.android.core.ReportUploader$Worker.onRun(ReportUploader.java:152)
  at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)

```

Looking at what is happening from AndroidStudio, we can see that bug is here:

```java
HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
    public boolean verify(String var1x, SSLSession var2) {
        if("videodev.ksyun.com".equals(var1x)) {
            return true;
        } else if("centertime.ksyun.com".equals(var1x)) {
            return true;
        } else {
            HostnameVerifier var3 = HttpsURLConnection.getDefaultHostnameVerifier();
            return var3.verify(var1x, var2);
        }
    }
});
```

So if all checks miss, we will call the same verifier and get StackOverFlow

**Comment by chriszeng87** [comment]
We have fixed this bug, and fixed version will be released next week. Thank you.

**Comment by vovkab** [comment]
@chriszeng87 thanks! Any idea when exactly new version will be pushed to public?
Or maybe you know what is latest unaffected version number is, so we can try to downgrade?

So far I tried 3 latest versions and they all crash.

**Comment by chriszeng87** [comment]
The fixed version is still in test and it will be released this week if no big bug found.

**Comment by InterstellarWalker** [comment]
这周还能更新新版本么

**Comment by chriszeng87** [comment]
不好意思，测试周末在加班，估计要下周了

**Comment by vovkab** [comment]
@chriszeng87 do you know what is latest version that do not have this bug we can use meanwhile?

**Comment by chriszeng87** [comment]
https://github.com/ksvc/KSYLive_Android/releases/tag/v2.2.6  The fixed version has released. So sorry, guys.

**Comment by vovkab** [comment]
@chriszeng87 thank you for fix!
