### ISSUE TITLE
乐视1s x500  anr sdk释放时死锁

### ISSUE THREAD

**Issue by IsaiahKing** [ksvc/KSYStreamer_Android#156]
配置如下
```
compile 'com.ksyun.media:libksylive-java:2.2.6'
compile 'com.ksyun.media:libksylive-armv7a:2.2.6'
compile 'com.ksyun.media:libksylive-arm64:2.2.6'
compile 'com.ksyun.media:libksylive-x86:2.2.6'
```

anr 线程日志

```
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x74c69000 self=0x42407800
  | sysTid=23224 nice=-6 cgrp=default sched=0/0 handle=0x4000eecc
  | state=S schedstat=( 34007561145 6551492956 95163 ) utm=2832 stm=568 core=1 HZ=100
  | stack=0xff543000-0xff545000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x04ce8db8> (a java.lang.Object)
  at java.lang.Thread.join(Thread.java:724)
  - locked <0x04ce8db8> (a java.lang.Object)
  at com.ksyun.media.streamer.capture.AudioCapture.release(AudioCapture.java:193)
  at com.ksyun.media.streamer.kit.KSYStreamer.release(KSYStreamer.java:2170)
  - locked <@addr=0x137d13c0> (a java.lang.Object)
  at com.es.live.basic.service.a.e.a(unavailable:-1)
  - locked <@addr=0x137d12b0> (a java.lang.Boolean)
  at com.es.live.basic.service.a.b.b(unavailable:-1)
  at com.es.live.ui.live.LiveActivity.a(LiveActivity.java:1856)
  at com.es.live.ui.live.LiveActivity.a(LiveActivity.java:178)
  at com.es.live.ui.live.LiveActivity$1.handleMessage(LiveActivity.java:461)
  at android.os.Handler.dispatchMessage(Handler.java:111)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5589)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
```

```
"AudioCapture" prio=10 tid=110 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x13105860 self=0x89948400
  | sysTid=28381 nice=-6 cgrp=default sched=0/0 handle=0x849ba000
  | state=S schedstat=( 126773778 65385453 805 ) utm=10 stm=2 core=1 HZ=100
  | stack=0x976f9000-0x976fb000 stackSize=1036KB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x0ae52ff4> (a java.lang.Object)
  at com.ksyun.media.streamer.capture.AudioCapture$a.run(AudioCapture.java:359)
  - locked <0x0ae52ff4> (a java.lang.Object)
  at java.lang.Thread.run(Thread.java:818)
```

**Comment by chriszeng87** [comment]
有logcat的日志么

**Comment by IsaiahKing** [comment]
logcat日志比较长， 需要什么哪一部分的，这个推流时间超过30分钟，现在判断是AudioCapture关闭失败导致的死锁，从定时轮询发现有时AudioCapture关闭的比较慢

在调用mKStreamer.stopStream()之后，如果下面状态持续过长就会死锁。
mKStreamer.getAudioCapture().isRecordingState()  为 true

**Comment by buliaoyin** [comment]
这个问题我们内部还没有复现出来，不过下个将发布版本的AudioCapture模块进行了比较大程度的优化，避免了锁的使用，应该能够完全避免这种问题

**Comment by fpzeng** [comment]
请使用新版本测试：https://github.com/ksvc/KSYStreamer_Android/releases/tag/v4.2.0

内部优化了同步机制，anr几率降低很多
