### ISSUE TITLE
crash on KSYStreamer v4.1.3.1 (Galaxy K Zoom - android 4.4.2)

### ISSUE THREAD

**Issue by linhphan-appsters** [ksvc/KSYStreamer_Android#159]
Fatal Exception: java.lang.NumberFormatException: Invalid double: "�34�447��44�313�-�v:"
       at java.lang.StringToReal.invalidReal(StringToReal.java:63)
       at java.lang.StringToReal.parseDouble(StringToReal.java:269)
       at java.lang.Double.parseDouble(Double.java:295)
       at java.lang.Double.valueOf(Double.java:332)
       at com.ksyun.media.streamer.util.f$a.onHttpResponse(TimeDeltaUtil.java:349)
       at com.ksyun.media.streamer.util.https.KsyHttpClient.onHttpResponse(KsyHttpClient.java:54)
       at com.ksyun.media.streamer.util.https.KsyHttpConnection$1.run(KsyHttpConnection.java:141)
       at java.lang.Thread.run(Thread.java:841)

**Comment by chriszeng87** [comment]
We have fixed this bug, please update the new version, thank you!

**Comment by linhphan-appsters** [comment]
Thank you so much for your efforts.
