### ISSUE TITLE
开始推流出现崩溃,log日志如下，是什么原因？

### ISSUE THREAD

**Issue by mghxz252** [ksvc/KSYStreamer_Android#172]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ksyun.media.streamer.publisher.PublisherWrapper.a(int, int, int, int, int)' on a null object reference
	at com.ksyun.media.streamer.publisher.RtmpPublisher.setBwEstConfig(RtmpPublisher.java:63)
	at com.ksyun.media.streamer.kit.KSYStreamer.setRecordingParams(KSYStreamer.java:1542)
	at com.ksyun.media.streamer.kit.KSYStreamer.startCapture(KSYStreamer.java:1601)
	at com.ksyun.media.streamer.kit.KSYStreamer.startStream(KSYStreamer.java:1566)
	at com.yimwing.cloud.ui.Live_ui.BoBo_KSYLiveActivity$6$2.run(BoBo_KSYLiveActivity.java:842)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5714)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by mghxz252** [comment]
还有一种崩溃 是这样的
java.lang.NullPointerException
	at com.ksyun.media.streamer.publisher.RtmpPublisher.setBwEstConfig(RtmpPublisher.java:63)
	at com.ksyun.media.streamer.kit.KSYStreamer.setRecordingParams(KSYStreamer.java:1542)
	at com.ksyun.media.streamer.kit.KSYStreamer.startCapture(KSYStreamer.java:1601)
	at com.ksyun.media.streamer.kit.KSYStreamer.startStream(KSYStreamer.java:1566)
	at com.yimwing.cloud.ui.Live_ui.BoBo_KSYLiveActivity$6$2.run(BoBo_KSYLiveActivity.java:842)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5137)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by chriszeng87** [comment]
帮忙用KSYStreamer.getVersion()看下版本？

**Comment by mghxz252** [comment]
版本号是：4.2.0.4  不是所有手机会这样，

**Comment by chriszeng87** [comment]
具体是什么机型会这样呢?系统版本号是?

**Comment by mghxz252** [comment]
(android;4.4.2)/tengxun (phone:NX505J) 还有这个

**Comment by mghxz252** [comment]
有人知道么？

**Comment by chriszeng87** [comment]
我们先确认下，稍等哈

**Comment by chriszeng87** [comment]
你应该是在release KSYStreamer后，继续对KSYStreamer做了操作，这个你确认下?

**Comment by mghxz252** [comment]
好的，谢谢
