### ISSUE TITLE
推流崩溃的问题 ，日志如下，这个是什么原因?

### ISSUE THREAD

**Issue by mghxz252** [ksvc/KSYStreamer_Android#196]
java.lang.ArrayIndexOutOfBoundsException: src.length=753 srcPos=0 dst.length=685 dstPos=-685 length=671
	at java.lang.System.arraycopy(Native Method)
	at java.lang.String._getChars(String.java:908)
	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:147)
	at java.lang.StringBuilder.append(StringBuilder.java:216)
	at com.ksyun.media.streamer.logstats.StatsLogReport.a(StatsLogReport.java:831)
	at com.ksyun.media.streamer.logstats.StatsLogReport.b(StatsLogReport.java:1168)
	at com.ksyun.media.streamer.logstats.StatsLogReport.reportError(StatsLogReport.java:640)
	at com.ksyun.media.streamer.encoder.Encoder$3.run(Encoder.java:458)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5398)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by chriszeng87** [comment]
用KSYStreamer.getVersion()看下版本号？

**Comment by mghxz252** [comment]
版本号是：4.2.0.4

**Comment by buliaoyin** [comment]
还请升级到最新版本再验证下是否还会出现该问题。

**Comment by mghxz252** [comment]
好的
