### ISSUE TITLE
java.lang.NoSuchMethodError: no method with name='onEncoded' 

### ISSUE THREAD

**Issue by curtis2** [ksvc/KSYStreamer_Android#208]
手机型号：华为  H60-L01
android版本：4.4.2
操作步骤，在直播的过程中，点击home键退出，就会抛这个异常！

TIME=1431972851000
FINGERPRINT=Huawei/H60-L01/hwH60:4.4.2/HDH60-L01/CHNC00B316:user/ota-rel-keys,release-keys
replacements=[Ljava.lang.String;@417fb030
HARDWARE=Kirin920
matchers=[Ljava.lang.String;@417fae30
UNKNOWN=unknown
RADIO=unknown
BOARD=H60-L01
PRODUCT=H60-L01
DISPLAY=H60-L01V100R001CHNC00B316
USER=jenkins
HOST=shacidculx1383
DEVICE=hwH60
HIDE_PRODUCT_INFO=false
TAGS=ota-rel-keys,release-keys
MODEL=H60-L01
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=false
ID=HDH60-L01
SERIAL=7N2SSE1534024464
MANUFACTURER=HUAWEI
BRAND=Huawei
TYPE=user
java.lang.NoSuchMethodError: no method with name='onEncoded' signature='(Ljava/nio/ByteBuffer;JJI)V' in class Lcom/ksyun/media/streamer/encoder/AVEncoderWrapper;
	at com.ksyun.media.streamer.encoder.AVEncoderWrapper._init(Native Method)
	at com.ksyun.media.streamer.encoder.AVEncoderWrapper.<init>(AVEncoderWrapper.java:38)
	at com.ksyun.media.streamer.encoder.AVCodecAudioEncoder.a(AVCodecAudioEncoder.java:40)
	at com.ksyun.media.streamer.encoder.Encoder$4.handleMessage(Encoder.java:503)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by buliaoyin** [comment]
还请确认用demo是否可以复现

**Comment by curtis2** [comment]
用demo复现不了。 可能是我调用方式不正确。这个能不能从代码分析是什么原因呢？

**Comment by buliaoyin** [comment]
对照demo看下onPause/onResume里面的处理吧。

然后仔细看下：https://github.com/ksvc/KSYStreamer_Android/wiki/Front_Back_Switch
