### ISSUE TITLE
java.lang.NullPointerException on AudioCapture.java

### ISSUE THREAD

**Issue by thanhbc** [ksvc/KSYStreamer_Android#265]
KSY version 
```java
public static String getVersion() {
        return "4.4.2.0";
    }
```

crash log:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
       at com.ksyun.media.streamer.capture.AudioCapture.a(AudioCapture.java:224)
       at com.ksyun.media.streamer.capture.AudioCapture.b(AudioCapture.java:32)
       at com.ksyun.media.streamer.capture.AudioCapture$a.run(AudioCapture.java:287)
```

**Comment by buliaoyin** [comment]
请尽量提供详细的crash复现步骤，用demo是否能够复现出该问题。

**Comment by thanhbc** [comment]
@buliaoyin 我们现在暂时还没找到复现的步骤，以上是在我们的crashlytic log 下来的。
![Uploading Screen Shot 2018-01-13 at 17.23.00.png…]()

**Comment by thanhbc** [comment]
可能`release KSYStreamer`后才出现这个crash。

**Comment by buliaoyin** [comment]
@thanhbc 先确认下是否有使用release后的KSYStreamer实例的情况吧。
