### ISSUE TITLE
java.util.ConcurrentModificationException on LogClient.java line 283

### ISSUE THREAD

**Issue by thanhbc** [ksvc/KSYStreamer_Android#266]
KSY version
```java
public static String getVersion() {
        return "4.4.2.0";
    }
```

crash log
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
       at java.util.HashMap$KeyIterator.next(HashMap.java:833)
       at com.ksy.statlibrary.log.LogClient$1.run(LogClient.java:283)
       at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by chriszeng87** [comment]
We have fixed this bug, please try our new version.
