### ISSUE TITLE
V5.0.1.3版本启动录像，偶尔出现NullPointerException

### ISSUE THREAD

**Issue by orange7** [ksvc/KSYStreamer_Android#284]
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@51477e0
versionCode=100
BOARD=MT6757
BOOTLOADER=C7100ZCU1AQL1
IS_TRANSLATION_ASSISTANT_ENABLED=false
TYPE=user
ID=NMF26X
TIME=1512445997000
BRAND=samsung
TAG=Build
HARDWARE=mt6757
SERIAL=420cab479a2084b9
SUPPORTED_ABIS=[Ljava.lang.String;@d7d7a99
CPU_ABI=armeabi-v7a
IS_DEBUGGABLE=false
RADIO=unknown
MANUFACTURER=samsung
IS_EMULATOR=false
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@87591e3
TAGS=release-keys
CPU_ABI2=armeabi
IS_SYSTEM_SECURE=false
UNKNOWN=unknown
PERMISSIONS_REVIEW_REQUIRED=false
USER=dpi
FINGERPRINT=samsung/jadeltezc/jadeltechn:7.1.1/NMF26X/C7100ZCU1AQL1:user/release-keys
HOST=SWDG5312
versionName=1.0.0
PRODUCT=jadeltezc
DISPLAY=NMF26X.C7100ZCU1AQL1
MODEL=SM-C7100
DEVICE=jadeltechn
IS_SECURE=false
java.lang.NullPointerException: Attempt to read from field 'int com.ksyun.media.streamer.framework.AudioCodecFormat.channels' on a null object reference
	at com.ksyun.media.streamer.encoder.MediaCodecAudioEncoder.a(MediaCodecAudioEncoder.java:41)
	at com.ksyun.media.streamer.encoder.Encoder$4.handleMessage(Encoder.java:542)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

APP运行崩溃前的日志：
09-04 18:55:35.207 24441-25105/com.oculi D/Publisher: Opening output file for writing at path /storage/emulated/0/Android/data/com.oculi/files/ATP/SOURCE/20180904185535/20180904185535.mp4
09-04 18:55:35.208 24441-25105/com.oculi D/Publisher: Connect to /storage/emulated/0/Android/data/com.oculi/files/ATP/SOURCE/20180904185535/20180904185535.mp4 success!
09-04 18:55:35.210 24441-24441/com.oculi D/KSYStreamer: file publisher info:1
09-04 18:55:35.211 24441-24533/com.oculi D/Encoder: config encoder width com.ksyun.media.streamer.framework.VideoCodecFormat@2987c45
09-04 18:55:35.211 24441-25108/com.oculi E/AndroidRuntime: FATAL EXCEPTION: EncodeThread
                                                           Process: com.oculi, PID: 24441
                                                           java.lang.NullPointerException: Attempt to read from field 'int com.ksyun.media.streamer.framework.AudioCodecFormat.channels' on a null object reference
                                                               at com.ksyun.media.streamer.encoder.MediaCodecAudioEncoder.a(MediaCodecAudioEncoder.java:41)
                                                               at com.ksyun.media.streamer.encoder.Encoder$4.handleMessage(Encoder.java:542)
                                                               at android.os.Handler.dispatchMessage(Handler.java:106)
                                                               at android.os.Looper.loop(Looper.java:164)
                                                               at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by orange7** [comment]
发现设置为软编码不会出现这个错误，但是硬编码的话，就会偶现，有的手机崩溃的概率高，有的手机概率低
