### ISSUE TITLE
Android studiso3.2.1 点击准备直播就崩溃，看到日志应该是ksylive.jar 没有找到c层的getStringList方法所致，怎么解决？

### ISSUE THREAD

**Issue by mxdldev** [ksvc/KSYStreamer_Android#292]
```
java.lang.UnsatisfiedLinkError: No implementation found for java.util.List com.ksyun.media.streamer.util.StringWrapper.getStringList() (tried Java_com_ksyun_media_streamer_util_StringWrapper_getStringList and Java_com_ksyun_media_streamer_util_StringWrapper_getStringList__)
        at com.ksyun.media.streamer.util.StringWrapper.getStringList(Native Method)
        at com.ksyun.media.streamer.util.StringWrapper.<init>(StringWrapper.java:42)
        at com.ksyun.media.streamer.util.StringWrapper.getInstance(StringWrapper.java:24)
        at com.ksyun.media.streamer.logstats.StatsLogReport.<init>(StatsLogReport.java:183)
        at com.ksyun.media.streamer.logstats.StatsLogReport.getInstance(StatsLogReport.java:161)
        at com.ksyun.media.streamer.kit.KSYStreamer.<init>(KSYStreamer.java:160)
        at com.ksyun.media.streamer.demo.AudioStreamingActivity.onCreate(AudioStreamingActivity.java:114)
        at android.app.Activity.performCreate(Activity.java:6942)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by EddyDaddy** [comment]
导入arm64的动态库，可以解决这个问题。当时奇怪的是官方推荐只用导入armabi-v7a

**Comment by TsuiOS** [comment]
java.lang.UnsatisfiedLinkError: No implementation found for java.util.List com.ksyun.media.streamer.util.StringWrapper.getStringList() (tried Java_com_ksyun_media_streamer_util_StringWrapper_getStringList and Java_com_ksyun_media_streamer_util_StringWrapper_getStringList__)
这个是怎么解决的

**Comment by 1330483851** [comment]
导入其他的so文件
