### ISSUE TITLE
java.lang.UnsatisfiedLinkError是什么原因

### ISSUE THREAD

**Issue by GuoCuiCow** [ksvc/KSYStreamer_Android#31]
我在尝试推流的时候，报错
08-09 18:59:56.531 14311-14448/cn.camhow.zhibo E/art: No implementation found for java.lang.String com.ksy.recordlib.service.stats.StreamLogWrapper.getLogAccessKeyNative() (tried Java_com_ksy_recordlib_service_stats_StreamLogWrapper_getLogAccessKeyNative and Java_com_ksy_recordlib_service_stats_StreamLogWrapper_getLogAccessKeyNative__)
08-09 18:59:56.531 14311-14448/cn.camhow.zhibo E/AndroidRuntime: FATAL EXCEPTION: Thread-1011
                                                                 Process: cn.camhow.zhibo, PID: 14311
                                                                 java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.ksy.recordlib.service.stats.StreamLogWrapper.getLogAccessKeyNative() (tried Java_com_ksy_recordlib_service_stats_StreamLogWrapper_getLogAccessKeyNative and Java_com_ksy_recordlib_service_stats_StreamLogWrapper_getLogAccessKeyNative__)
                                                                     at com.ksy.recordlib.service.stats.StreamLogWrapper.getLogAccessKeyNative(Native Method)
                                                                     at com.ksy.recordlib.service.stats.StreamLogWrapper.c(Unknown Source)
                                                                     at com.ksy.recordlib.service.stats.b.run(Unknown Source)
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by chriszeng87** [comment]
jar的版本和so的版本不一致，请同步更新jar和so

**Comment by GuoCuiCow** [comment]
我试了一下github上最新的，还有直接用demo工程里面的，都是报同样的错误

**Comment by chriszeng87** [comment]
今天或者明天会发布新版本解决这个问题

**Comment by fpzeng** [comment]
v3.3.0.8已经修复这个问题，请更新版本试试

**Comment by GuoCuiCow** [comment]
谢谢

**Comment by SunnyBoolean** [comment]
请问是什么错误：UnsatisfiedLinkError：
java.lang.UnsatisfiedLinkError: No implementation found for java.util.List com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.getContentList() (tried Java_com_ksy_recordlib_service_hardware_ksyfilter_KSYCredtpWrapper_getContentList and Java_com_ksy_recordlib_service_hardware_ksyfilter_KSYCredtpWrapper_getContentList__)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.getContentList(Native Method)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.<init>(Unknown Source)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.hardware.ksyfilter.KSYCredtpWrapper.a(Unknown Source)
08-15 14:07:13.580 1808-1808/com.geo.ksmdemo E/AndroidRuntime:     at com.ksy.recordlib.service.hardware.ksyfilter.KSYImageFilter.<init>(Unknown Source)

**Comment by GuoCuiCow** [comment]
帮忙和你们的WPS同事说一声啊，装了wps之后没办法真机调试，一直强迫断开我的adb，只好卸载了·

**Comment by zanxiaofei** [comment]
@SunnyBoolean 是找不到实现，实现参数名有点问题，在有的机器找不到
