### ISSUE TITLE
Monkey测试一定概率Crash问题(或者内存回收)

### ISSUE THREAD

**Issue by wangwangheng** [ksvc/KSYStreamer_Android#39]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView.setLayoutParams(android.view.ViewGroup$LayoutParams)' on a null object reference
	at com.ksy.recordlib.service.core.h.p(Unknown Source)
	at com.ksy.recordlib.service.core.h.m(Unknown Source)
	at com.ksy.recordlib.service.core.h$a.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5628)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)

**Comment by zanxiaofei** [comment]
从log信息上看，应该是GLSurfaceView被回收了，但是KSYStreamer可能没有释放。我们加个容错吧

**Comment by wangwangheng** [comment]
@zanxiaofei  这个问题在哪个版本解决？TKS！

**Comment by zanxiaofei** [comment]
@wangwangheng 3.3.2.0 本周五发
