### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for long com.ksyun.media.streamer.util.audio.KSYBgmPlayer._init()

### ISSUE THREAD

**Issue by GuoCuiCow** [ksvc/KSYStreamer_Android#69]
`mStreamer = new KSYStreamer(this);`
在初始化的时候报这个错误
`10-17 11:11:11.919 26613-26613/cn.com.camhow.live E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: cn.com.camhow.live, PID: 26613
                                                                    java.lang.UnsatisfiedLinkError: No implementation found for long com.ksyun.media.streamer.util.audio.KSYBgmPlayer._init() (tried Java_com_ksyun_media_streamer_util_audio_KSYBgmPlayer__1init and Java_com_ksyun_media_streamer_util_audio_KSYBgmPlayer__1init__)
                                                                        at com.ksyun.media.streamer.util.audio.KSYBgmPlayer._init(Native Method)
                                                                        at com.ksyun.media.streamer.util.audio.KSYBgmPlayer.<init>(KSYBgmPlayer.java:79)
                                                                        at com.ksyun.media.streamer.capture.AudioPlayerCapture.<init>(AudioPlayerCapture.java:24)
                                                                        at com.ksyun.media.streamer.kit.KSYStreamer.initModules(KSYStreamer.java:168)
                                                                        at com.ksyun.media.streamer.kit.KSYStreamer.<init>(KSYStreamer.java:107)
                                                                        at cn.com.camhow.live.activity.CameraActivity.onCreate(CameraActivity.java:216)
                                                                        at android.app.Activity.performCreate(Activity.java:5975)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                        at android.os.Looper.loop(Looper.java:194)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)`

**Comment by GuoCuiCow** [comment]
已经定位到bug了，是一个布局写错了，但是没想到ide居然报的是ksy的bug

**Comment by VipMinF** [comment]
请问这个错误是怎么引起。怎么解决的。 可以分享下嘛？

**Comment by Wwq-Scofield** [comment]
太久了，真的忘了
