### ISSUE TITLE
crashed on API level 15 android device

### ISSUE THREAD

**Issue by kingbeful** [ksvc/KSYStreamer_Android#71]
Hi, 

I'm using a moto atrix2 (aka. MB865) with android 4.0.4 (API level 15)
When I runs the KSYStreamer to publish a stream, the app crashed with error:

`E/AndroidRuntime: FATAL EXCEPTION: GLThread 343
                                                                     java.lang.NoClassDefFoundError: android.opengl.EGL14
                                                                         at com.ksyun.media.streamer.util.gles.b.<init>(EglStateSaver.java:21)
                                                                         at com.ksyun.media.streamer.util.gles.b.a(EglStateSaver.java:30)
                                                                         at com.ksyun.media.streamer.util.gles.GLRender.a(GLRender.java:159)
                                                                         at com.ksyun.media.streamer.util.gles.GLRender.a(GLRender.java:22)
                                                                         at com.ksyun.media.streamer.util.gles.e.onSurfaceCreated(GLRender.java:210)
                                                                         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1471)
                                                                         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1241)`

IMOH, the main reason for this error is KSY SDK using EGL14 which available in API level 17

pls check this link for more info https://codereview.webrtc.org/1396013004/

**Comment by buliaoyin** [comment]
Thanks for your feedback, we will check this issue.

**Comment by buliaoyin** [comment]
Fix in v4.0.1，please check.

**Comment by kingbeful** [comment]
It works. Thank you
