### ISSUE TITLE
Samsung S4 i9500 crashed with log

### ISSUE THREAD

**Issue by kingbeful** [ksvc/KSYStreamer_Android#77]
When I start to publish stream, my i9500 crashed with log reports:

I/StreamSucessCount: begin to send success count: http://videodev.ksyun.com:8980/univ/clientcounter?accesskey=D8uDWZ88ZKW48/eZHmRm&expire=1477300491&cont=eyJzZGtfdHlwZSI6InN0cmVhbWVyIiwic2RrX3ZlciI6IjQuMC4xLjAiLCJzZGtfdmVyX3N1YiI6IjQuMC4xLjAiLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJvc192ZXIiOiI1LjAuMSIsInBrZyI6IlVOS05PV04iLCJkZXZfbW9kZWwiOiJHVC1JOTUwMCIsImRldl9pZCI6IlVOS05PV04iLCJsb2dfdmVyIjoiMS4wLjIiLCJsb2dfdm4iOjEwMX0%3D&uniqname=ksystreamer_android&signature=L%2FkVK1Vvd6XsKf4la4GPJCehMF8%3D
E/ImageReader_JNI: Producer output buffer format: 0x5, ImageReader configured format: 0x1
E/AndroidRuntime: FATAL EXCEPTION: EncodeThread
                                                                       Process: com.xxx.live.demo, PID: 21765
                                                                       java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.
                                                                           at android.media.ImageReader.nativeImageSetup(Native Method)
                                                                           at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:297)
                                                                           at android.media.ImageReader.acquireNextImage(ImageReader.java:343)
                                                                           at com.ksyun.media.streamer.encoder.a.onImageAvailable(AVCodecSurfaceEncoder.java:93)
                                                                           at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:547)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:145)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
I/StatsLogReport: dns check ClientIP:116.226.176.202
I/StatsLogReport: dns check LocalDnsIp:116.228.111.12
I/StatsLogReport: dns check result:200
I/Publish: ***onLogEvent : {"_id":"a9dc2eb1-ca04-442b-9c8a-57346f048eed","type":100,"body_type":"connectionStatus","action_id":"13AE037FBA8B36C579E64D97EDA91CF2","streamId":"13AE037FBA8B36C579E64D97EDA91CF2","dns_dt":8,"dns_ip":"116.228.111.12","connectDt":138,"date":1477299893203}

Would you check the reason?

Thank you

**Comment by chriszeng87** [comment]
We have fixed this bug, new version will be release this week.

**Comment by kingbeful** [comment]
May I know the release day？

**Comment by chriszeng87** [comment]
It should be today, but we have another bug....

**Comment by chriszeng87** [comment]
Fixed already, please try new version.
