### ISSUE TITLE
三星note3  android4.4.4系统推流出现格子奇葩现象

### ISSUE THREAD

**Issue by Goach** [ksvc/KSYStreamer_Android#81]
java.lang.RuntimeException: createWindowSurface failed EGL_BAD_ALLOC
	at android.view.HardwareRenderer$GlRenderer.createSurface(HardwareRenderer.java:1349)
	at android.view.HardwareRenderer$GlRenderer.createEglSurface(HardwareRenderer.java:1241)
	at android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:1058)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1546)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5001)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by buliaoyin** [comment]
推流SDK版本？从log看应该是3.x版本，还请升级至最新版本再确认。

**Comment by Goach** [comment]
推流SDK版本4.0.0

**Comment by buliaoyin** [comment]
还请提供更详细的信息，比如具体的调用方式，复现步骤等。

**Comment by Goach** [comment]
我们也是在线用户提供的bug，其他手机都是正常的，就这个手机会这样。这个日志我也是友盟统计获取的。调用方式就是使用4.0.0demo里面的配置，大概配置如下

    private void initKsyStream(){
        mMainHandler = new Handler();
        mStreamer = new KSYStreamer(this);
        mStreamer.setIFrameInterval(1.5f);
        if (frameRate > 0){
            mStreamer.setPreviewFps(frameRate);
            mStreamer.setTargetFps(frameRate);
        }
        if (videoBitrate > 0) {
            videoBitrate *= 1000;
            mStreamer.setVideoBitrate(videoBitrate * 3 / 4, videoBitrate, videoBitrate / 4);
        }
        if (audioBitrate > 0)
            mStreamer.setAudioBitrate(audioBitrate * 1000);
        mStreamer.setPreviewResolution(videoResolution);
        mStreamer.setTargetResolution(videoResolution);
        mStreamer.setEncodeMethod(encode_method);
        mStreamer.setRotateDegrees(landscape ? 90 : 0);
        setRequestedOrientation(landscape?ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE:ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
        mStreamer.setFrontCameraMirror(false);
        mStreamer.setDisplayPreview(mCameraPreview);
        mStreamer.setEnableStreamStatModule(true);
        mStreamer.enableDebugLog(HoomicConstans.logON);
        mStreamer.toggleTorch(false);
        mStreamer.setMuteAudio(false);
        mStreamer.setEnableAudioPreview(false);
        mStreamer.hideWaterMarkLogo();
        mStreamer.hideWaterMarkTime();
        mStreamer.setOnInfoListener(this);
        mStreamer.setOnErrorListener(this);
        mStreamer.getImgTexFilterMgt().setFilter(mStreamer.getGLRender(),ImgTexFilterMgt.KSY_FILTER_BEAUTY_DENOISE);
        mStreamer.setEnableImgBufBeauty(true);
    }

    @Override
    public void onResume() {
        super.onResume();
        mStreamer.startCameraPreview();
        mStreamer.onResume();
        if (mStreamer.isRecording()) {
            mStreamer.setAudioOnly(false);
        }
    }


 @Override
    public void onPause() {
        super.onPause();
        mStreamer.onPause();
        mStreamer.stopCameraPreview();
    }

 private void startLive(){
        mStreamer.startStream();
    }
现象就是
![mmexport1478529597223](https://cloud.githubusercontent.com/assets/13835896/20085048/272c81ec-a5a1-11e6-92c6-28d65c36a63a.jpg)

**Comment by buliaoyin** [comment]
这个现象还是比较奇怪的，我们会尝试复现看看。

**Comment by Goach** [comment]
好的，

**Comment by Goach** [comment]
我在夜神模拟器启动也是这样，这是因为没有摄像头的原因吗？？

**Comment by chriszeng87** [comment]
请用最新版本试试，已经修复
