### ISSUE TITLE
初始化KSYStreamer崩溃，魅族MX4 Android 5.1 融合版v2.0.0

### ISSUE THREAD

**Issue by Bill2048** [ksvc/KSYStreamer_Android#87]
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long com.ksyun.media.streamer.util.audio.KSYBgmPlayer._init() (tried Java_com_ksyun_media_streamer_util_audio_KSYBgmPlayer__1init and Java_com_ksyun_media_streamer_util_audio_KSYBgmPlayer__1init__)
	at com.ksyun.media.streamer.util.audio.KSYBgmPlayer._init(Native Method)
	at com.ksyun.media.streamer.util.audio.KSYBgmPlayer.<init>(KSYBgmPlayer.java:79)
	at com.ksyun.media.streamer.capture.AudioPlayerCapture.<init>(AudioPlayerCapture.java:24)
	at com.ksyun.media.streamer.kit.KSYStreamer.initModules(KSYStreamer.java:165)
	at com.ksyun.media.streamer.kit.KSYStreamer.<init>(KSYStreamer.java:104)

**Comment by buliaoyin** [comment]
还请先验证jar包与so库是否已正确替换
