### ISSUE TITLE
在推流过程中发现的一个崩溃，日志如下

### ISSUE THREAD

**Issue by pzhangleo** [ksvc/KSYStreamer_Android#91]
java.lang.IllegalStateException: Unbalanced enter/exit
	at com.android.okhttp.okio.AsyncTimeout.enter(AsyncTimeout.java:62)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:905)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:150)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:210)
	at io.bugtags.agent.instrumentation.TransactionStateUtil.fillHttpURLConnectionData(TransactionStateUtil.java:89)
	at io.bugtags.agent.instrumentation.httpurl.HttpURLConnectionExtension.addTransactionAndErrorData(HttpURLConnectionExtension.java:449)
	at io.bugtags.agent.instrumentation.httpurl.HttpURLConnectionExtension.disconnect(HttpURLConnectionExtension.java:50)
	at com.ksy.recordlib.service.util.https.b.a(Unknown Source)
	at com.ksy.recordlib.service.util.https.KsyHttpClient.cancelHttpRequest(Unknown Source)

**Comment by pzhangleo** [comment]
请参考下Okhttp的issue，https://github.com/square/okhttp/issues/1842
应该不可以在不同的线程调用disconnect
